spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres



#    currentSchema=service