spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    username: postgres
    password: root
    url: jdbc:postgresql://192.168.99.3:5432/postgres?currentSchema=service